export const GET_ALL_POST = "GET_ALL_POST";
export const GET_ALL_POST_SUCCESS = "GET_ALL_POST_SUCCESS";
export const GET_ALL_POST_FAILED = "GET_ALL_POST_FAILED";

export const GET_ALL_COMMENT_BY_POST_ID = "GET_ALL_COMMENT_BY_POST_ID";
export const GET_ALL_COMMENT_BY_POST_ID_SUCCESS =
  "GET_ALL_COMMENT_BY_POST_ID_SUCCESS";
export const GET_ALL_COMMENT_BY_POST_ID_FAILED =
  "GET_ALL_COMMENT_BY_POST_ID_FAILED";

export const GET_DETAIL_POST = "GET_DETAIL_POST";
export const GET_DETAIL_POST_SUCCESS = "GET_DETAIL_POST_SUCCESS";
export const GET_DETAIL_POST_FAILED = "GET_DETAIL_POST_FAILED";
